from __future__ import annotations

import re

from airas.core.research_paths import RECORD_PATH
from airas.core.types.paper_values import PaperValue

VALUES_TEX_FILENAME = "values.tex"

_HEADER = (
    "% AUTO-GENERATED by the update_record tool. DO NOT EDIT.\n"
    "% verify_paper_values regenerates this file from record.json and the\n"
    "% run outputs and fails on any difference, so manual edits always surface."
)

# Characters safe both in a URL and inside \href's first argument (a %
# would comment out the rest of the line, a # would break macro parsing).
_URL_SAFE = re.compile(r"^[A-Za-z0-9:/._~-]+$")


def record_blob_url(repo_url: str | None, ref: str | None) -> str | None:
    """Link into the record at a pinned commit.

    A branch link would resolve to whatever the record says later — it keeps
    growing — so the link names the commit that last wrote it, which is the
    state that produced the number being clicked. Both parts are derived at
    render time (the origin remote, the commit that wrote the record) rather
    than stored in the record, which has no reason to know where it lives.
    """
    if not ref or not repo_url:
        return None
    url = f"{repo_url}/blob/{ref}/{RECORD_PATH}"
    return url if _URL_SAFE.match(url) else None


def render_values_tex(
    values: list[PaperValue], repo_url: str | None, ref: str | None = None
) -> str:
    url = record_blob_url(repo_url, ref)
    lines = [
        _HEADER,
        r"\makeatletter",
        r"\newcommand{\airasval}[1]{\@ifundefined{airasval@#1}"
        r"{\airasvalmissing{#1}}{\csname airasval@#1\endcsname}}",
        r"\newcommand{\airasvalmissing}[1]{\textbf{??airasval:\detokenize{#1}??}}",
        r"\providecommand{\unverified}[1]{#1}",
        # \ifdefined at use time: hyperref may load after this file (mdpi
        # loads it at begindocument), and without it the value stays plain.
        (
            rf"\newcommand{{\airasrecordlink}}[1]{{\ifdefined\href"
            rf"\href{{{url}}}{{#1}}\else#1\fi}}"
            if url
            else r"\newcommand{\airasrecordlink}[1]{#1}"
        ),
    ]
    for value in values:
        if value.derivation:
            lines.append(f"% {value.ref} = {value.derivation}")
        lines.append(
            rf"\expandafter\def\csname airasval@{value.ref}\endcsname"
            rf"{{\airasrecordlink{{{value.display}}}}}"
        )
    lines.append(r"\makeatother")
    return "\n".join(lines) + "\n"
