from __future__ import annotations

import re

from airas.core.research_paths import RECORD_PATH
from airas.core.types.paper_record import LinkBase
from airas.core.types.paper_values import ComputedValue

VALUES_TEX_FILENAME = "values.tex"

_HEADER = (
    "% AUTO-GENERATED by the update_and_verify_record tool. DO NOT EDIT.\n"
    "% verify_paper_values regenerates this file from record.json and the\n"
    "% run outputs and fails on any difference, so manual edits always surface."
)

# Characters safe both in a URL and inside \href's first argument (a %
# would comment out the rest of the line, a # would break macro parsing).
_URL_SAFE = re.compile(r"^[A-Za-z0-9:/._~-]+$")


def record_blob_url(link_base: LinkBase) -> str | None:
    url = f"{link_base.repo_url}/blob/{link_base.ref}/{RECORD_PATH}"
    return url if _URL_SAFE.match(url) else None


def render_values_tex(values: list[ComputedValue], link_base: LinkBase | None) -> str:
    url = record_blob_url(link_base) if link_base else None
    lines = [
        _HEADER,
        r"\makeatletter",
        r"\newcommand{\airasval}[1]{\@ifundefined{airasval@#1}"
        r"{\airasvalmissing{#1}}{\csname airasval@#1\endcsname}}",
        r"\newcommand{\airasvalmissing}[1]{\textbf{??airasval:\detokenize{#1}??}}",
        r"\providecommand{\unverified}[1]{#1}",
        # \ifdefined at use time: hyperref may load after this file (mdpi
        # loads it at begindocument), and without it the value stays plain.
        (
            rf"\newcommand{{\airasrecordlink}}[1]{{\ifdefined\href"
            rf"\href{{{url}}}{{#1}}\else#1\fi}}"
            if url
            else r"\newcommand{\airasrecordlink}[1]{#1}"
        ),
    ]
    for value in values:
        derivation = f"{value.op}({', '.join(value.refs)})"
        if value.round is not None:
            derivation += f" round {value.round}"
        lines.append(f"% {value.key} = {derivation}")
        lines.append(
            rf"\expandafter\def\csname airasval@{value.key}\endcsname"
            rf"{{\airasrecordlink{{{value.display}}}}}"
        )
    lines.append(r"\makeatother")
    return "\n".join(lines) + "\n"
