from __future__ import annotations

from typing import Any

from airas.core.types.paper_values import TableSpec
from airas.usecases.publication.paper_values.compute import (
    format_display,
    match_run_id,
    resolve_ref,
)

TABLES_DIR_NAME = "tables"

_HEADER = (
    "% AUTO-GENERATED by the update_and_verify_record tool. DO NOT EDIT.\n"
    "% verify_paper_values regenerates this file from record.json and the\n"
    "% run outputs and fails on any difference, so manual edits always surface."
)


def table_tex_relpath(key: str) -> str:
    return f"{TABLES_DIR_NAME}/{key}.tex"


def render_table_tex(spec: TableSpec, metrics_data: dict[str, Any]) -> str:
    # Core LaTeX only (no booktabs), so the output compiles under every
    # bundled template. The cell at (row, column) is always
    # <row.run_id>.<column.ref_path>: a label cannot be paired with
    # another run's number.
    column_layout = "l" + "r" * len(spec.columns)
    header_cells = [""] + [column.header for column in spec.columns]

    lines = [
        _HEADER,
        r"\begin{table}[t]",
        r"\centering",
        rf"\caption{{{spec.caption}}}",
        rf"\label{{{spec.label or f'tab:{spec.key}'}}}",
        rf"\begin{{tabular}}{{{column_layout}}}",
        r"\hline",
        " & ".join(header_cells) + r" \\",
        r"\hline",
    ]
    for row in spec.rows:
        cells = [row.label]
        for column in spec.columns:
            value = resolve_ref(metrics_data, f"{row.run_id}.{column.ref_path}")
            cells.append(format_display(value, column.round))
        lines.append(" & ".join(cells) + r" \\")
    lines += [r"\hline", r"\end{tabular}", r"\end{table}"]
    return "\n".join(lines) + "\n"


def table_result_dirs(specs: list[TableSpec], metrics_data: dict[str, Any]) -> set[str]:
    return {
        d
        for spec in specs
        for row in spec.rows
        if (d := match_run_id(metrics_data, row.run_id)) is not None
    }
