"""Deterministic rendering of declared results tables.

The agent declares *which* runs and metrics appear where (a TableSpec);
this module reads the actual numbers from the run outputs and renders the
tabular. Because the cell at (row, column) is always
`<row.run_id>.<column.ref_path>`, a table cannot pair a method's label
with another run's number — the swap that free-hand LaTeX tables allow.
Verification regenerates every table from tables.json and byte-compares,
so hand edits to the rendered files surface the same way values.tex
edits do.
"""

from __future__ import annotations

from typing import Any

from airas.core.types.paper_values import PaperTables, TableSpec
from airas.usecases.publication.paper_values.compute import (
    format_display,
    resolve_ref,
)

TABLES_JSON_FILENAME = "tables.json"
TABLES_DIR_NAME = "tables"

_HEADER = (
    "% AUTO-GENERATED by the compute_paper_tables tool. DO NOT EDIT.\n"
    "% verify_paper_values regenerates this file from the run outputs and\n"
    "% fails on any difference, so manual edits always surface."
)


def table_tex_relpath(key: str) -> str:
    """Path of a table's rendered file, relative to the LaTeX directory."""
    return f"{TABLES_DIR_NAME}/{key}.tex"


def render_table_tex(spec: TableSpec, metrics_data: dict[str, Any]) -> str:
    """Render one declared table from the measured metrics.

    Uses only core LaTeX (no booktabs or array packages), so the output
    compiles under every bundled template.
    """
    column_layout = "l" + "r" * len(spec.columns)
    header_cells = [""] + [column.header for column in spec.columns]

    lines = [
        _HEADER,
        r"\begin{table}[t]",
        r"\centering",
        rf"\caption{{{spec.caption}}}",
        rf"\label{{{spec.label or f'tab:{spec.key}'}}}",
        rf"\begin{{tabular}}{{{column_layout}}}",
        r"\hline",
        " & ".join(header_cells) + r" \\",
        r"\hline",
    ]
    for row in spec.rows:
        cells = [row.label]
        for column in spec.columns:
            value = resolve_ref(metrics_data, f"{row.run_id}.{column.ref_path}")
            cells.append(format_display(value, column.round))
        lines.append(" & ".join(cells) + r" \\")
    lines += [r"\hline", r"\end{tabular}", r"\end{table}"]
    return "\n".join(lines) + "\n"


def compute_paper_tables(
    specs: list[TableSpec], metrics_data: dict[str, Any]
) -> tuple[PaperTables, dict[str, str]]:
    """Render every declared table; returns the record and key -> tex."""
    seen: set[str] = set()
    rendered: dict[str, str] = {}
    for spec in specs:
        if spec.key in seen:
            raise ValueError(f"duplicate table key '{spec.key}'")
        seen.add(spec.key)
        rendered[spec.key] = render_table_tex(spec, metrics_data)
    return PaperTables(tables=specs), rendered


def table_result_dirs(tables: PaperTables) -> set[str]:
    """Every results directory the declared tables draw numbers from."""
    return {row.run_id for spec in tables.tables for row in spec.rows}
