### E2E - Dispatch Task

POST http://localhost:8001/airas/v1/e2e/run
Content-Type: application/json

{
    "github_config": {
        "github_owner": "auto-res2",
        "repository_name": "test-tanaka-20260102",
        "branch_name": "main-14"
    },
    "research_topic": "efficient LLM optimization",
    "runner_config": {
        "runner_label": ["self-hosted", "gpu-runner"],
        "description": "NVIDIA A100 or H200, VRAM: 80 GB or more, RAM: 2048 GB or more"
    },
    "wandb_config": {
        "entity": "toma_tanaka",
        "project": "2026-01-02"
    },
    "is_github_repo_private": false,
    "num_paper_search_queries": 1,
    "papers_per_query": 2,
    "hypothesis_refinement_iterations": 1,
    "num_experiment_models": 1,
    "num_experiment_datasets": 1,
    "num_comparison_methods": 1,
    "experiment_code_validation_iterations": 2,
    "paper_content_refinement_iterations": 1,
    "latex_template_name": "iclr2024"
}

###

### E2E - Poll Task Status

GET http://localhost:8000/airas/v1/e2e/status/8344c5d5-3094-4ec2-8154-3ea423b671ae
