### E2E - Dispatch Task

POST http://localhost:8000/airas/v1/e2e/run
Content-Type: application/json

{
  "github_config": {
    "github_owner": "auto-res2",
    "repository_name": "test-matsuzawa-20251219",
    "branch_name": "main"
  },
  "query_list": [
    "Learning rate"
  ],
  "runner_config": {
    "runner_label": ["self-hosted", "gpu-runner"],
    "description": "NVIDIA A100 or H200, VRAM: 80 GB or more, RAM: 2048 GB or more"
  },
  "wandb_config": {
    "entity": "gengaru617-personal",
    "project": "2025-11-19"
  },
  "is_private": false,
  "max_results_per_query": 5,
  "refinement_rounds": 1,
  "num_models_to_use": 1,
  "num_datasets_to_use": 1,
  "num_comparative_methods": 1,
  "max_code_validations": 10,
  "writing_refinement_rounds": 2,
  "latex_template_name": "iclr2024"
}

###

### E2E - Poll Task Status

GET http://localhost:8000/airas/v1/e2e/status/8344c5d5-3094-4ec2-8154-3ea423b671ae
