### Poll github actions status
POST http://127.0.0.1:8000/airas/v1/github-actions/polling
Content-Type: application/json

{
    "github_config": {
        "github_owner": "auto-res2",
        "repository_name": "your-repo",
        "branch_name": "your-branch"
    }
}

### Set github actions secrets
POST http://127.0.0.1:8000/airas/v1/github-actions/secrets
Content-Type: application/json

{
    "github_config": {
        "github_owner": "auto-res2",
        "repository_name": "e2e-test-matsuzawa-20260128",
        "branch_name": "main"
    }
}

###

### Download github actions artifacts
POST http://127.0.0.1:8000/airas/v1/github-actions/artifacts/download
Content-Type: application/json

{
    "github_config": {
        "github_owner": "auto-res2",
        "repository_name": "matsuzawa-2026-02-10",
        "branch_name": "main"
    },
    "workflow_run_id": 21867996671
}

###
