### Create session

POST http://127.0.0.1:8000/airas/v1/sessions
Content-Type: application/json

{
    "title": "ddd"
}


### Get session

GET http://127.0.0.1:8000/airas/v1/sessions/cf2775e0-0b16-40c4-a78e-cb8eb683a995
Content-Type: application/json
