write_paper_prompt = """\
You are writing `.research/latex/{template}/main.tex` of a preregistered \
study — at preregistration, before any experiment has run, or after the \
runs have results. The commit that adds the preregistration paper is the \
freeze point; after results, the legitimate diff is what the results force.

## What you work from
`.research/record.json` — the hypothesis, the claims, and every source with \
its bibkey and passages. Cite a source with `\\cite{key}`; a sentence resting on a \
registered passage cites it as `\\cite[s1.p2]{key}`, and the gate checks \
the passage belongs to that source. If main.tex exists, revise it; do not \
start over.

## Structure: two parts
The frozen part — title, abstract, introduction, related work, hypothesis \
and predictions, method, experimental design — is written in full at \
preregistration. The post-experiment part — Results and Discussion — is \
left as stubs behind the marker comment

    % ===== airas: post-experiment sections, filled once runs exist =====

so the diff at publish time is confined to a region a reviewer can find.

The hypothesis and predictions section is `\\input{claims.tex}`: the file \
is rendered from record.json (Hypothesis 1, Claim 1, Claim 2, … with \
rationale, cited passages, criterion, predicted interval and verdict, then \
the assumptions) and regenerated by \
the gate, so the list in the PDF is the record's, not a transcription. \
Prose around it may explain why each criterion and interval was chosen.

## Numbers
Every experimental number is `\\airasval{key}` and appears only in the \
post-experiment part — never a literal, not even an expected one presented \
as measured. `\\airasval` addresses `<run_id>.<metric.path>` (a metric of \
a declared run) or `<run_id>.params.<key>` (a condition the run was \
declared with). A number no declaration can produce (e.g. quoted from a \
cited paper) is wrapped as `\\unverified{...}`. Tables come from \
`tables/<key>.tex`, rendered from the record's table declarations. The \
preamble must compile without values.tex:

    \\InputIfFileExists{values.tex}{}{}
    \\providecommand{\\airasval}[1]{\\textbf{??airasval:\\detokenize{#1}??}}
    \\providecommand{\\unverified}[1]{#1}
    \\providecommand{\\airasrecordlink}[1]{#1}

Put `\\airasrecordlink{record.json}` in the Data Availability statement. \
(`\\providecommand` is a no-op once values.tex defines the macros; do not \
move these into an `\\IfFileExists` branch.)

## Language and engine
Write in the user's working language. A CJK paper needs a LuaTeX preamble \
(`luatexja-fontspec`); with the `mdpi` class also \
`\\RequirePackage{luatex85}` before `\\documentclass` and no `pdftex` \
option. The template directory is only a slot — keep the usual structure \
(title, abstract, numbered sections, figures, bibliography); \
`references.bib` is rendered from the record, never edit it.

## After the experiments (once run outputs exist)
Results and Discussion are written now, in the stub region: every claim \
reported by number against its criterion and predicted interval, with \
`\\airasval` for every value. Do not edit the claims to fit the results. A \
criterion that fails is a negative result: keep the claim, report that it \
did not hold, and discuss why. A value that meets the criterion but misses \
the interval is reported as such. A new finding is a new claim appended \
via `append_to_record` and presented as exploratory. `verified: true` \
says the claim's data is in, not that it held — `verdict` does.
Produce the complete main.tex as `{"main_tex": "..."}`.
"""
