from __future__ import annotations

import re

AUTO_GENERATED_HEADER = (
    "% AUTO-GENERATED by the update_record tool. DO NOT EDIT.\n"
    "% verify_paper regenerates this file from record.json and the run outputs\n"
    "% and fails on any difference, so manual edits always surface."
)


# Record text reaches pdflatex verbatim, so LaTeX's specials are escaped and
# the symbols a Lean statement carries become math macros (pdflatex has no
# text glyph for `∀` or `ℕ`). ponytail: the table is the symbols seen in Lean
# statements so far; add an entry when a paper needs another, or switch to
# pylatexenc if the list keeps growing. Other non-ASCII text passes through —
# the engine and fonts are the author's choice.
_LATEX_TEXT = {
    **{c: f"\\{c}" for c in "&%$#_{}"},
    "\\": r"\textbackslash{}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
    "∀": r"$\forall$",
    "∃": r"$\exists$",
    "∑": r"$\sum$",
    "∈": r"$\in$",
    "→": r"$\to$",
    "≤": r"$\leq$",
    "≥": r"$\geq$",
    "≠": r"$\neq$",
    "¬": r"$\neg$",
    "∧": r"$\wedge$",
    "∨": r"$\vee$",
    "ℕ": r"$\mathbb{N}$",
    "ℤ": r"$\mathbb{Z}$",
    "ℚ": r"$\mathbb{Q}$",
    "ℝ": r"$\mathbb{R}$",
    "²": r"$^{2}$",
}


_LATEX_TEXT_RE = re.compile("|".join(re.escape(k) for k in _LATEX_TEXT))


def latex_text(text: str) -> str:
    """`text` as pdflatex can typeset it in text mode."""
    return _LATEX_TEXT_RE.sub(lambda m: _LATEX_TEXT[m.group(0)], text)
