from __future__ import annotations

import re
import unicodedata
from pathlib import Path

import bibtexparser
from bibtexparser.bibdatabase import BibDatabase

from airas.core.research_paths import REFERENCES_BIB_FILENAME
from airas.core.types.research_record import LiteratureSource, ResearchRecord


def _ascii(text: str) -> str:
    # "Müller" keys as muller, not mller.
    decomposed = unicodedata.normalize("NFKD", text)
    return "".join(c for c in decomposed if not unicodedata.combining(c))


def _citation_key(title: str, authors: list[str], year: int | None) -> str:
    # Sources disagree on author formatting: OpenAlex/arXiv return
    # "Ashish Vaswani" while Semantic Scholar can return "Vaswani, Ashish".
    author = _ascii(authors[0].strip()) if authors else ""
    surname = author.split(",", 1)[0] if "," in author else (author.split() or [""])[-1]
    surname = re.sub(r"[^a-z0-9]", "", surname.lower()) or "author"
    words = re.findall(r"\b[a-zA-Z]{3,}\b", _ascii(title).lower())
    return f"{surname}-{year or 'year'}-{words[0] if words else 'title'}"


def _disambiguation_suffix(occurrence: int) -> str:
    suffix = ""
    while occurrence > 0:
        occurrence, remainder = divmod(occurrence - 1, 26)
        suffix = chr(ord("a") + remainder) + suffix
    return suffix


def unique_bibkey(
    title: str, authors: list[str], year: int | None, taken: set[str]
) -> str:
    base = _citation_key(title, authors, year)
    key, occurrence = base, 0
    while key in taken:
        occurrence += 1
        key = f"{base}{_disambiguation_suffix(occurrence)}"
    return key


def render_references_bib(literature: list[LiteratureSource]) -> str:
    """One entry per source under its bibkey; regenerated by the gate."""
    db = BibDatabase()
    for source in literature:
        entry = {
            "ID": source.bibkey,
            "ENTRYTYPE": "article" if source.kind == "paper" else "misc",
            "title": source.title,
        }
        if source.authors:
            entry["author"] = " and ".join(source.authors)
        if source.year:
            entry["year"] = str(source.year)
        if source.venue:
            entry["journal"] = source.venue
        if source.doi:
            entry["doi"] = source.doi
        if source.url:
            entry["url"] = source.url
        if source.commit:
            entry["note"] = f"commit {source.commit}"
        db.entries.append(entry)
    return bibtexparser.dumps(db).strip() + "\n"


def write_references_bib(local_path: str, template: str, record: ResearchRecord) -> str:
    relpath = f".research/latex/{template}/{REFERENCES_BIB_FILENAME}"
    path = Path(local_path).expanduser().resolve() / relpath
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_references_bib(record.active_literature()), encoding="utf-8")
    return relpath
