name: oss-webapp

services:
  backend:
    build:
      context: ./backend
    env_file:
      - .env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      target: prod
    env_file:
      - .env
    ports:
      - "5173:80"
    depends_on:
      - backend
