# Curated model registry — time_series / forecasting. Part of the shared
# domain>category taxonomy across resources/{libraries,models,datasets}.
# HuggingFace URLs and arXiv citations are verified on entry; use
# search_huggingface_hub for un-curated needs.
FORECASTING_MODELS: dict = {
    "chronos-t5-small": {
        "description": "",
        "model_parameters": "46M",
        "model_architecture": "Pretrained time-series forecasting model.",
        "domain": "time_series",
        "category": "forecasting",
        "task_type": "time-series-forecasting",
        "huggingface_url": "https://huggingface.co/amazon/chronos-t5-small",
        "dependent_packages": ["transformers", "torch"],
        "code": "",
        "citation": """@misc{ansari2024,
  title = {Chronos: Learning the Language of Time Series},
  author = {Abdul Fatir Ansari and Lorenzo Stella and Caner Turkmen and Xiyuan Zhang and Pedro Mercado and Huibin Shen and Oleksandr Shchur and Syama Sundar Rangapuram and Sebastian Pineda Arango and Shubham Kapoor and Jasper Zschiegner and Danielle C. Maddix and Hao Wang and Michael W. Mahoney and Kari Torkkola and Andrew Gordon Wilson and Michael Bohlke-Schneider and Yuyang Wang},
  year = {2024},
  eprint = {2403.07815},
  archivePrefix = {arXiv},
  url = {https://arxiv.org/abs/2403.07815}
}""",
        "training_data_sources": "",
    },
    "timesfm-1.0-200m": {
        "description": "",
        "model_parameters": "Unknown",
        "model_architecture": "Pretrained time-series forecasting model.",
        "domain": "time_series",
        "category": "forecasting",
        "task_type": "time-series-forecasting",
        "huggingface_url": "https://huggingface.co/google/timesfm-1.0-200m",
        "dependent_packages": ["transformers", "torch"],
        "code": "",
        "citation": """@misc{das2023,
  title = {A decoder-only foundation model for time-series forecasting},
  author = {Abhimanyu Das and Weihao Kong and Rajat Sen and Yichen Zhou},
  year = {2023},
  eprint = {2310.10688},
  archivePrefix = {arXiv},
  url = {https://arxiv.org/abs/2310.10688}
}""",
        "training_data_sources": "",
    },
    "patchtst-forecasting": {
        "description": "",
        "model_parameters": "1M",
        "model_architecture": "Pretrained time-series forecasting model.",
        "domain": "time_series",
        "category": "forecasting",
        "task_type": "time-series-forecasting",
        "huggingface_url": "https://huggingface.co/ibm-granite/granite-timeseries-patchtst",
        "dependent_packages": ["transformers", "torch"],
        "code": "",
        "citation": """@misc{nie2022,
  title = {A Time Series is Worth 64 Words: Long-term Forecasting with Transformers},
  author = {Yuqi Nie and Nam H. Nguyen and Phanwadee Sinthong and Jayant Kalagnanam},
  year = {2022},
  eprint = {2211.14730},
  archivePrefix = {arXiv},
  url = {https://arxiv.org/abs/2211.14730}
}""",
        "training_data_sources": "",
    },
    "moirai-1.0-r-small": {
        "description": "",
        "model_parameters": "14M",
        "model_architecture": "Pretrained time-series forecasting model.",
        "domain": "time_series",
        "category": "forecasting",
        "task_type": "time-series-forecasting",
        "huggingface_url": "https://huggingface.co/Salesforce/moirai-1.0-R-small",
        "dependent_packages": ["transformers", "torch"],
        "code": "",
        "citation": """@misc{woo2024,
  title = {Unified Training of Universal Time Series Forecasting Transformers},
  author = {Gerald Woo and Chenghao Liu and Akshat Kumar and Caiming Xiong and Silvio Savarese and Doyen Sahoo},
  year = {2024},
  eprint = {2402.02592},
  archivePrefix = {arXiv},
  url = {https://arxiv.org/abs/2402.02592}
}""",
        "training_data_sources": "",
    },
}
