from __future__ import annotations

import subprocess
import tempfile
import unicodedata
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import bibtexparser
import feedparser
import httpx
from bibtexparser.bibdatabase import BibDatabase

from airas.core.research_paths import FULLTEXT_FILENAME, PAGE_SEPARATOR, SOURCES_DIR
from airas.core.types.research_record import (
    InputRef,
    LiteratureSource,
    ResearchRecord,
)
from airas.infra.arxiv_client import ArxivClient
from airas.usecases.recording.update_or_load_record import file_sha256
from airas.usecases.retrieve.search_papers_subgraph.nodes.search_airas_db import (
    _parse_authors,
)
from airas.usecases.writers.generate_bibfile_subgraph.nodes.generate_bibfile import (
    _disambiguation_suffix,
    _generate_citation_key,
)


def write_fulltext(root: Path, source_id: str, pages: list[str]) -> InputRef:
    relpath = f"{SOURCES_DIR}/{source_id}/{FULLTEXT_FILENAME}"
    path = root / relpath
    path.parent.mkdir(parents=True, exist_ok=True)
    if any(p.is_symlink() for p in (path, *path.parents[:2])) or not (
        path.resolve().is_relative_to(root.resolve())
    ):
        raise ValueError(f"{relpath} is a symlink or leaves the repository")
    path.write_text(PAGE_SEPARATOR.join(pages), encoding="utf-8")
    return InputRef(path=relpath, sha256=file_sha256(path))


def _normalize(text: str) -> str:
    # Ligatures, soft hyphens and line breaks are the extractor's, not the author's.
    return " ".join(unicodedata.normalize("NFKC", text).replace("­", "").split())


def quote_in(fulltext: str, quote: str) -> bool:
    needle = _normalize(quote)
    return bool(needle) and needle in _normalize(fulltext)


def next_source_id(record: ResearchRecord) -> str:
    return f"s{max((int(s.id[1:]) for s in record.literature), default=0) + 1}"


def next_passage_id(source: LiteratureSource) -> str:
    taken = (int(p.id.rsplit(".p", 1)[1]) for p in source.passages)
    return f"{source.id}.p{max(taken, default=0) + 1}"


def unique_bibkey(
    title: str, authors: list[str], year: int | None, taken: set[str]
) -> str:
    base = _generate_citation_key(title, authors, year)
    key, occurrence = base, 0
    while key in taken:
        occurrence += 1
        key = f"{base}{_disambiguation_suffix(occurrence)}"
    return key


def render_references_bib(literature: list[LiteratureSource]) -> str:
    """One entry per source under its bibkey; regenerated by the gate."""
    db = BibDatabase()
    for source in literature:
        entry = {
            "ID": source.bibkey,
            "ENTRYTYPE": "misc" if source.kind == "repository" else "article",
            "title": source.title,
        }
        if source.authors:
            entry["author"] = " and ".join(source.authors)
        if source.year:
            entry["year"] = str(source.year)
        if source.venue:
            entry["journal"] = source.venue
        if source.doi:
            entry["doi"] = source.doi
        if source.url:
            entry["url"] = source.url
        if source.commit:
            entry["note"] = f"commit {source.commit}"
        db.entries.append(entry)
    return bibtexparser.dumps(db).strip() + "\n"


def airas_db_metadata(record: dict[str, Any]) -> dict[str, Any]:
    year = record.get("year")
    paper_url = record.get("paper_url")
    return {
        "title": record.get("title") or "",
        "authors": _parse_authors(record.get("authors")),
        "year": int(year) if year else None,
        "venue": record.get("conference") or "",
        "url": paper_url if paper_url and paper_url != "None" else None,
    }


def snapshot_repository(
    url: str, commit: str, files: list[str]
) -> tuple[dict[str, Any], list[str]]:
    """Metadata and one snapshot page per file, read from `commit` of the
    repository at `url`; the fetch succeeding is what confirms it exists."""
    with tempfile.TemporaryDirectory() as tmp:

        def git(*args: str) -> str:
            done = subprocess.run(
                ["git", "-C", tmp, *args], capture_output=True, text=True, timeout=300
            )
            if done.returncode != 0:
                raise ValueError(
                    f"git {args[0]} failed for {url}@{commit}: {done.stderr.strip()}"
                )
            return done.stdout

        git("init", "-q")
        git("fetch", "-q", "--depth", "1", url, commit)
        pages = [
            f"==> {path} <==\n{git('show', f'FETCH_HEAD:{path}')}" for path in files
        ]
        year = int(git("log", "-1", "--format=%cs", "FETCH_HEAD")[:4])
    name = url.rstrip("/").removesuffix(".git").rsplit("/", 2)
    return (
        {
            "title": "/".join(name[-2:]),
            "authors": name[-2:-1],
            "year": year,
            "url": url,
            "commit": commit,
        },
        pages,
    )


async def verify_existence(
    *,
    airas_db_record: dict[str, Any] | None,
    doi: str | None,
    arxiv_id: str | None,
    arxiv: ArxivClient,
    http: httpx.AsyncClient,
) -> tuple[dict[str, str], str]:
    """registry -> found | not_found | 'error: ...' for the registry behind
    each identifier given, and when it was asked. The same check for a paper
    from airas-papers-db and for one the agent found on the web."""
    # TODO: OpenAlex / Semantic Scholar could confirm and enrich too; skipped
    # because the indexers miss papers the resolvers know.
    registries: dict[str, str] = {}
    if airas_db_record is not None:
        registries["airas_db"] = "found" if airas_db_record else "not_found"

    if doi:
        try:
            response = await http.head(
                f"https://doi.org/{doi}", timeout=30.0, follow_redirects=False
            )
            registries["doi.org"] = (
                "found"
                if response.is_redirect or response.is_success
                else "not_found"
                if response.status_code == 404
                else f"error: {response.status_code}"
            )
        except httpx.HTTPError as e:
            registries["doi.org"] = f"error: {e}"

    if arxiv_id:
        try:
            feed = feedparser.parse(await arxiv.aget_paper_by_id(arxiv_id))
            registries["arxiv"] = "found" if feed.entries else "not_found"
        except Exception as e:
            registries["arxiv"] = f"error: {e}"
    return registries, datetime.now(timezone.utc).isoformat(timespec="seconds")
