import logging

from airas.services.api_client.github_client import GithubClient

logger = logging.getLogger(__name__)


def edit_latex_file(
    github_owner: str,
    repository_name: str,
    branch_name: str,
    tex_text: str,
    latex_template_style: str,
) -> bool:
    client = GithubClient()

    target_path = f".research/latex/{latex_template_style}/paper.tex"
    is_latex_file_edited = client.commit_file_bytes(
        github_owner=github_owner,
        repository_name=repository_name,
        branch_name=branch_name,
        file_path=target_path,
        file_content=tex_text.encode(encoding="utf-8"),
        commit_message=f"Upload latex file for {branch_name}",
    )

    return is_latex_file_edited


if __name__ == "__main__":
    success = edit_latex_file(
        github_owner="auto-res2",
        repository_name="tanaka-20250729-v3",
        branch_name="main",
        tex_text=r"""\PassOptionsToPackage{numbers}{natbib}
\documentclass{article} % For LaTeX2e
\usepackage{iclr2024_conference,times}

\usepackage[utf8]{inputenc} % allow utf-8 input
\usepackage[T1]{fontenc} % use 8-bit T1 fonts
\usepackage{hyperref} % hyperlinks
\usepackage{url} % simple URL typesetting
\usepackage{booktabs} % professional-quality tables
\usepackage{amsfonts} % blackboard math symbols
\usepackage{nicefrac} % compact symbols for 1/2, etc.
\usepackage{microtype} % microtypography
\usepackage{titletoc}

\usepackage{subcaption}
\usepackage{graphicx}
\usepackage{amsmath}
\usepackage{multirow}
\usepackage{color}
\usepackage{colortbl}
\usepackage{cleveref}
\usepackage{algorithm}
\usepackage{algorithmicx}
\usepackage{algpseudocode}
\usepackage{tikz}
\usepackage{pgfplots}
\usepackage{float}
\usepackage{array}
\usepackage{tabularx}
\pgfplotsset{compat=newest}

\DeclareMathOperator*{\argmin}{arg\,min}
\DeclareMathOperator*{\argmax}{arg\,max}

\graphicspath{{../}} % To reference your generated figures, see below.

\title{TITLE HERE}

\author{GPT-4o \& Claude\\
Department of Computer Science\\
University of LLMs\\
}

\newcommand{\fix}{\marginpar{FIX}}
\newcommand{\new}{\marginpar{NEW}}

\begin{document}

\maketitle

\begin{abstract}
This is a sample abstract.
\end{abstract}

\section{Introduction}
\label{sec:intro}

This is a sample introduction.

\begin{figure}[H]
\centering
\includegraphics[width=0.8\linewidth]{figure1.png}
\caption{Sample figure 1 in introduction.}
\end{figure}

\section{Related Work}
\label{sec:related}
RELATED WORK HERE

\section{Background}
\label{sec:background}
BACKGROUND HERE

\section{Method}
\label{sec:method}

This is a sample method section.

\begin{figure}[H]
\centering
\includegraphics[width=0.8\linewidth]{figure2.jpg}
\caption{Sample figure 2 in method.}
\end{figure}

% Removed figure that referenced an unavailable image (figure3.jpg).

\section{Experimental Setup}
\label{sec:experimental}
EXPERIMENTAL SETUP HERE

\section{Results}
\label{sec:results}

These are the sample results.

\section{Results}
More sample results here.

\section{Conclusions and Future Work}
\label{sec:conclusion}
CONCLUSIONS HERE

This work was generated by \textsc{AIRAS} \citep{airas2025}.

\bibliographystyle{iclr2024_conference}
\bibliography{references}

\end{document}""",
        latex_template_style="iclr2024",
    )
    print(f"Latex file edited successfully: {success}")
