from logging import getLogger

from jinja2 import Environment
from pydantic import BaseModel

from airas.types.paper import PaperContent

logger = getLogger(__name__)


class LLMOutput(BaseModel):
    latex_text: str


def embed_in_latex_template(
    latex_formatted_paper_content: PaperContent,
    latex_template_text: str,
) -> str:
    data = {
        "title": latex_formatted_paper_content.title,
        "abstract": latex_formatted_paper_content.abstract,
        "introduction": latex_formatted_paper_content.introduction,
        "related_work": latex_formatted_paper_content.related_work,
        "background": latex_formatted_paper_content.background,
        "method": latex_formatted_paper_content.method,
        "experimental_setup": latex_formatted_paper_content.experimental_setup,
        "results": latex_formatted_paper_content.results,
        "conclusion": latex_formatted_paper_content.conclusion,
    }

    env = Environment(variable_start_string="<<", variable_end_string=">>")
    template = env.from_string(latex_template_text)
    latex_text = template.render(data)
    return latex_text


if __name__ == "__main__":
    llm_name = "o3-mini-2025-01-31"
    latex_formatted_paper_content = {
        "title": "Sample Paper Title",
        "abstract": "This is a sample abstract.",
        "introduction": "This is a sample introduction.",
        "related_work": "This is a sample related work.",
        "background": "This is a sample background.",
        "method": "This is a sample method.",
        "experimental_setup": "This is a sample experimental setup.",
        "results": "These are the sample results.",
        "conclusion": "This is a sample conclusion.",
    }

    references_bib = """\
@article{ref1,
title={Sample Reference},
author={Doe, John},
journal={Sample Journal},
year={2025}
}"""

    image_file_name_list = ["figure1.png", "figure2.jpg"]
    latex_template = r"""\
\PassOptionsToPackage{numbers}{natbib}
\documentclass{article} % For LaTeX2e
\usepackage{iclr2024_conference,times}

\usepackage[utf8]{inputenc} % allow utf-8 input
\usepackage[T1]{fontenc}    % use 8-bit T1 fonts
\usepackage{hyperref}       % hyperlinks
\usepackage{url}            % simple URL typesetting
\usepackage{booktabs}       % professional-quality tables
\usepackage{amsfonts}       % blackboard math symbols
\usepackage{nicefrac}       % compact symbols for 1/2, etc.
\usepackage{microtype}      % microtypography
\usepackage{titletoc}

\usepackage{subcaption}
\usepackage{graphicx}
\usepackage{amsmath}
\usepackage{multirow}
\usepackage{color}
\usepackage{colortbl}
\usepackage{cleveref}
\usepackage{algorithm}
\usepackage{algorithmicx}
\usepackage{algpseudocode}
\usepackage{tikz}
\usepackage{pgfplots}
\usepackage{float}
\usepackage{array}
\usepackage{tabularx}
\pgfplotsset{compat=newest}

\DeclareMathOperator*{\argmin}{arg\,min}
\DeclareMathOperator*{\argmax}{arg\,max}

\graphicspath{{../}} % To reference your generated figures, see below.

\title{ << title >> }

\author{AIRAS}

\newcommand{\fix}{\marginpar{FIX}}
\newcommand{\new}{\marginpar{NEW}}

\begin{document}

\maketitle

\begin{abstract}
<< abstract >>
\end{abstract}

\section{Introduction}
\label{sec:intro}
<< introduction >>


\begin{figure}[H]
\centering
\includegraphics[width=0.8\linewidth]{figure1.png}
\caption{Sample figure 1 in introduction.}
\end{figure}

\section{Related Work}
\label{sec:related}
<< related_work >>

\section{Background}
\label{sec:background}
<< background >>

\section{Method}
\label{sec:method}
<< method >>

\begin{figure}[H]
\centering
\includegraphics[width=0.8\linewidth]{figure2.jpg}
\caption{Sample figure 2 in method.}
\end{figure}

% Removed figure that referenced an unavailable image (figure3.jpg).

\section{Experimental Setup}
\label{sec:experimental}
<< experimental_setup >>

\section{Results}
\label{sec:results}
<< results >>


\section{Conclusions}
\label{sec:conclusion}
<< conclusion >>

This work was generated by \textsc{AIRAS} \citep{airas2025}.

\bibliographystyle{iclr2024_conference}
\bibliography{references}

\end{document}
"""

    result = embed_in_latex_template(
        latex_formatted_paper_content=latex_formatted_paper_content,
        latex_template_text=latex_template,
        references_bib=references_bib,
        figures_name=image_file_name_list,
        llm_name=llm_name,
    )

    print(result)
