# Canonical documentation endpoints for libraries commonly used in AIRAS
# experiments. Instead of vendoring library documentation (which goes stale),
# agents fetch the living docs at experiment-code-writing time; `llms_txt` is
# the machine-readable entry point where the project publishes one.
# Every URL here was verified reachable when added; when adding an entry,
# check the URLs (curl) rather than guessing them.
LIBRARY_DOCS: dict[str, dict[str, str | None]] = {
    "unsloth": {
        "description": "Memory-efficient LLM fine-tuning and RL (2x faster, ~70% less VRAM)",
        "category": "fine_tuning",
        "official_docs": "https://docs.unsloth.ai",
        "github": "https://github.com/unslothai/unsloth",
        "llms_txt": "https://docs.unsloth.ai/llms.txt",
        "llms_full_txt": "https://docs.unsloth.ai/llms-full.txt",
    },
    "axolotl": {
        "description": "Config-driven post-training for LLMs (full/LoRA/QLoRA fine-tuning)",
        "category": "fine_tuning",
        "official_docs": "https://docs.axolotl.ai",
        "github": "https://github.com/axolotl-ai-cloud/axolotl",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "peft": {
        "description": "Parameter-efficient fine-tuning methods (LoRA, prompt tuning, ...)",
        "category": "fine_tuning",
        "official_docs": "https://huggingface.co/docs/peft",
        "github": "https://github.com/huggingface/peft",
        "llms_txt": "https://huggingface.co/docs/peft/llms.txt",
        "llms_full_txt": None,
    },
    "llama-factory": {
        "description": "Unified fine-tuning framework for 100+ LLMs/VLMs with a web UI",
        "category": "fine_tuning",
        "official_docs": "https://llamafactory.readthedocs.io/en/latest",
        "github": "https://github.com/hiyouga/LlamaFactory",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "trl": {
        "description": "Post-training with RL: SFT, DPO, GRPO, PPO, reward modeling",
        "category": "post_training",
        "official_docs": "https://huggingface.co/docs/trl",
        "github": "https://github.com/huggingface/trl",
        "llms_txt": "https://huggingface.co/docs/trl/llms.txt",
        "llms_full_txt": None,
    },
    "openrlhf": {
        "description": "High-performance RLHF framework built on Ray and vLLM",
        "category": "post_training",
        "official_docs": "https://openrlhf.readthedocs.io/en/latest",
        "github": "https://github.com/OpenRLHF/OpenRLHF",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "verl": {
        "description": "RL training library for LLMs (volcano engine RLHF)",
        "category": "post_training",
        "official_docs": "https://verl.readthedocs.io/en/latest",
        "github": "https://github.com/verl-project/verl",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "deepspeed": {
        "description": "Distributed training/inference with ZeRO memory optimization",
        "category": "distributed_training",
        "official_docs": "https://www.deepspeed.ai",
        "github": "https://github.com/deepspeedai/DeepSpeed",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "accelerate": {
        "description": "Run the same PyTorch code on any distributed setup",
        "category": "distributed_training",
        "official_docs": "https://huggingface.co/docs/accelerate",
        "github": "https://github.com/huggingface/accelerate",
        "llms_txt": "https://huggingface.co/docs/accelerate/llms.txt",
        "llms_full_txt": None,
    },
    "pytorch-lightning": {
        "description": "High-level PyTorch training framework (Trainer, callbacks, DDP)",
        "category": "distributed_training",
        "official_docs": "https://lightning.ai/docs/pytorch/stable",
        "github": "https://github.com/Lightning-AI/pytorch-lightning",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "ray": {
        "description": "Distributed compute for scaling training, tuning, and serving",
        "category": "distributed_training",
        "official_docs": "https://docs.ray.io/en/latest",
        "github": "https://github.com/ray-project/ray",
        "llms_txt": "https://docs.ray.io/llms.txt",
        "llms_full_txt": "https://docs.ray.io/llms-full.txt",
    },
    "megatron-core": {
        "description": "NVIDIA library for large-scale transformer training (TP/PP/SP)",
        "category": "distributed_training",
        "official_docs": "https://docs.nvidia.com/megatron-core/developer-guide/latest",
        "github": "https://github.com/NVIDIA/Megatron-LM",
        # Site-wide index linking per-product NVIDIA llms.txt files
        "llms_txt": "https://docs.nvidia.com/llms.txt",
        "llms_full_txt": None,
    },
    "vllm": {
        "description": "High-throughput LLM serving (PagedAttention, continuous batching)",
        "category": "inference_serving",
        "official_docs": "https://docs.vllm.ai",
        "github": "https://github.com/vllm-project/vllm",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "sglang": {
        "description": "Fast LLM serving with RadixAttention and structured generation",
        "category": "inference_serving",
        "official_docs": "https://docs.sglang.ai",
        "github": "https://github.com/sgl-project/sglang",
        "llms_txt": "https://docs.sglang.ai/llms.txt",
        "llms_full_txt": "https://docs.sglang.ai/llms-full.txt",
    },
    "tensorrt-llm": {
        "description": "NVIDIA-optimized LLM inference engine for TensorRT",
        "category": "inference_serving",
        "official_docs": "https://nvidia.github.io/TensorRT-LLM",
        "github": "https://github.com/NVIDIA/TensorRT-LLM",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "llama-cpp": {
        "description": "CPU/GPU LLM inference in C/C++ with GGUF quantized models",
        "category": "inference_serving",
        "official_docs": "https://github.com/ggml-org/llama.cpp",
        "github": "https://github.com/ggml-org/llama.cpp",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "bitsandbytes": {
        "description": "8-bit/4-bit quantization and optimizers for PyTorch",
        "category": "optimization",
        "official_docs": "https://huggingface.co/docs/bitsandbytes",
        "github": "https://github.com/bitsandbytes-foundation/bitsandbytes",
        "llms_txt": "https://huggingface.co/docs/bitsandbytes/llms.txt",
        "llms_full_txt": None,
    },
    "flash-attention": {
        "description": "Fused attention kernels (FlashAttention 2/3) for memory and speed",
        "category": "optimization",
        "official_docs": "https://github.com/Dao-AILab/flash-attention",
        "github": "https://github.com/Dao-AILab/flash-attention",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "lm-eval-harness": {
        "description": "Standard few-shot evaluation harness for language models",
        "category": "evaluation",
        "official_docs": "https://github.com/EleutherAI/lm-evaluation-harness",
        "github": "https://github.com/EleutherAI/lm-evaluation-harness",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "wandb": {
        "description": "Experiment tracking, sweeps, and artifact management",
        "category": "experiment_tracking",
        "official_docs": "https://docs.wandb.ai",
        "github": "https://github.com/wandb/wandb",
        "llms_txt": "https://docs.wandb.ai/llms.txt",
        "llms_full_txt": "https://docs.wandb.ai/llms-full.txt",
    },
    "mlflow": {
        "description": "Open-source ML lifecycle platform (tracking, models, registry)",
        "category": "experiment_tracking",
        "official_docs": "https://mlflow.org/docs/latest",
        "github": "https://github.com/mlflow/mlflow",
        "llms_txt": "https://mlflow.org/llms.txt",
        "llms_full_txt": None,
    },
    "transformers": {
        "description": "Pretrained model library and training utilities (Trainer)",
        "category": "core",
        "official_docs": "https://huggingface.co/docs/transformers",
        "github": "https://github.com/huggingface/transformers",
        "llms_txt": "https://huggingface.co/docs/transformers/llms.txt",
        "llms_full_txt": None,
    },
    "datasets": {
        "description": "Loading, processing, and streaming of ML datasets",
        "category": "core",
        "official_docs": "https://huggingface.co/docs/datasets",
        "github": "https://github.com/huggingface/datasets",
        "llms_txt": "https://huggingface.co/docs/datasets/llms.txt",
        "llms_full_txt": None,
    },
    "pytorch": {
        "description": "Core deep learning framework",
        "category": "core",
        "official_docs": "https://docs.pytorch.org/docs/stable",
        "github": "https://github.com/pytorch/pytorch",
        "llms_txt": None,
        "llms_full_txt": None,
    },
}
