# Canonical documentation endpoints for libraries commonly used in AIRAS
# experiments. Instead of vendoring library documentation (which goes stale),
# agents fetch the living docs at experiment-code-writing time; `llms_txt` is
# the machine-readable entry point where the project publishes one.
# Every URL here was verified reachable when added; when adding an entry,
# check the URLs (curl) rather than guessing them.
LIBRARY_DOCS: dict[str, dict[str, str | None]] = {
    "unsloth": {
        "description": "Memory-efficient LLM fine-tuning and RL (2x faster, ~70% less VRAM)",
        "category": "fine_tuning",
        "official_docs": "https://docs.unsloth.ai",
        "github": "https://github.com/unslothai/unsloth",
        "llms_txt": "https://docs.unsloth.ai/llms.txt",
        "llms_full_txt": "https://docs.unsloth.ai/llms-full.txt",
    },
    "axolotl": {
        "description": "Config-driven post-training for LLMs (full/LoRA/QLoRA fine-tuning)",
        "category": "fine_tuning",
        "official_docs": "https://docs.axolotl.ai",
        "github": "https://github.com/axolotl-ai-cloud/axolotl",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "peft": {
        "description": "Parameter-efficient fine-tuning methods (LoRA, prompt tuning, ...)",
        "category": "fine_tuning",
        "official_docs": "https://huggingface.co/docs/peft",
        "github": "https://github.com/huggingface/peft",
        "llms_txt": "https://huggingface.co/docs/peft/llms.txt",
        "llms_full_txt": "https://huggingface.co/docs/peft/llms-full.txt",
    },
    "llama-factory": {
        "description": "Unified fine-tuning framework for 100+ LLMs/VLMs with a web UI",
        "category": "fine_tuning",
        "official_docs": "https://llamafactory.readthedocs.io/en/latest",
        "github": "https://github.com/hiyouga/LlamaFactory",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "trl": {
        "description": "Post-training with RL: SFT, DPO, GRPO, PPO, reward modeling",
        "category": "post_training",
        "official_docs": "https://huggingface.co/docs/trl",
        "github": "https://github.com/huggingface/trl",
        "llms_txt": "https://huggingface.co/docs/trl/llms.txt",
        "llms_full_txt": "https://huggingface.co/docs/trl/llms-full.txt",
    },
    "openrlhf": {
        "description": "High-performance RLHF framework built on Ray and vLLM",
        "category": "post_training",
        "official_docs": "https://openrlhf.readthedocs.io/en/latest",
        "github": "https://github.com/OpenRLHF/OpenRLHF",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "verl": {
        "description": "RL training library for LLMs (volcano engine RLHF)",
        "category": "post_training",
        "official_docs": "https://verl.readthedocs.io/en/latest",
        "github": "https://github.com/verl-project/verl",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "deepspeed": {
        "description": "Distributed training/inference with ZeRO memory optimization",
        "category": "distributed_training",
        "official_docs": "https://www.deepspeed.ai",
        "github": "https://github.com/deepspeedai/DeepSpeed",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "accelerate": {
        "description": "Run the same PyTorch code on any distributed setup",
        "category": "distributed_training",
        "official_docs": "https://huggingface.co/docs/accelerate",
        "github": "https://github.com/huggingface/accelerate",
        "llms_txt": "https://huggingface.co/docs/accelerate/llms.txt",
        "llms_full_txt": "https://huggingface.co/docs/accelerate/llms-full.txt",
    },
    "pytorch-lightning": {
        "description": "High-level PyTorch training framework (Trainer, callbacks, DDP)",
        "category": "distributed_training",
        "official_docs": "https://lightning.ai/docs/pytorch/stable",
        "github": "https://github.com/Lightning-AI/pytorch-lightning",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "ray": {
        "description": "Distributed compute for scaling training, tuning, and serving",
        "category": "distributed_training",
        "official_docs": "https://docs.ray.io/en/latest",
        "github": "https://github.com/ray-project/ray",
        "llms_txt": "https://docs.ray.io/llms.txt",
        "llms_full_txt": "https://docs.ray.io/llms-full.txt",
    },
    "megatron-core": {
        "description": "NVIDIA library for large-scale transformer training (TP/PP/SP)",
        "category": "distributed_training",
        "official_docs": "https://docs.nvidia.com/megatron-core/developer-guide/latest",
        "github": "https://github.com/NVIDIA/Megatron-LM",
        # Site-wide index linking per-product NVIDIA llms.txt files
        "llms_txt": "https://docs.nvidia.com/llms.txt",
        "llms_full_txt": None,
    },
    "vllm": {
        "description": "High-throughput LLM serving (PagedAttention, continuous batching)",
        "category": "inference_serving",
        "official_docs": "https://docs.vllm.ai",
        "github": "https://github.com/vllm-project/vllm",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "sglang": {
        "description": "Fast LLM serving with RadixAttention and structured generation",
        "category": "inference_serving",
        "official_docs": "https://docs.sglang.ai",
        "github": "https://github.com/sgl-project/sglang",
        "llms_txt": "https://docs.sglang.ai/llms.txt",
        "llms_full_txt": "https://docs.sglang.ai/llms-full.txt",
    },
    "tensorrt-llm": {
        "description": "NVIDIA-optimized LLM inference engine for TensorRT",
        "category": "inference_serving",
        "official_docs": "https://nvidia.github.io/TensorRT-LLM",
        "github": "https://github.com/NVIDIA/TensorRT-LLM",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "llama-cpp": {
        "description": "CPU/GPU LLM inference in C/C++ with GGUF quantized models",
        "category": "inference_serving",
        "official_docs": "https://github.com/ggml-org/llama.cpp",
        "github": "https://github.com/ggml-org/llama.cpp",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "bitsandbytes": {
        "description": "8-bit/4-bit quantization and optimizers for PyTorch",
        "category": "optimization",
        "official_docs": "https://huggingface.co/docs/bitsandbytes",
        "github": "https://github.com/bitsandbytes-foundation/bitsandbytes",
        "llms_txt": "https://huggingface.co/docs/bitsandbytes/llms.txt",
        "llms_full_txt": "https://huggingface.co/docs/bitsandbytes/llms-full.txt",
    },
    "flash-attention": {
        "description": "Fused attention kernels (FlashAttention 2/3) for memory and speed",
        "category": "optimization",
        "official_docs": "https://github.com/Dao-AILab/flash-attention",
        "github": "https://github.com/Dao-AILab/flash-attention",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "lm-eval-harness": {
        "description": "Standard few-shot evaluation harness for language models",
        "category": "evaluation",
        "official_docs": "https://github.com/EleutherAI/lm-evaluation-harness",
        "github": "https://github.com/EleutherAI/lm-evaluation-harness",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "wandb": {
        "description": "Experiment tracking, sweeps, and artifact management",
        "category": "experiment_tracking",
        "official_docs": "https://docs.wandb.ai",
        "github": "https://github.com/wandb/wandb",
        "llms_txt": "https://docs.wandb.ai/llms.txt",
        "llms_full_txt": "https://docs.wandb.ai/llms-full.txt",
    },
    "mlflow": {
        "description": "Open-source ML lifecycle platform (tracking, models, registry)",
        "category": "experiment_tracking",
        "official_docs": "https://mlflow.org/docs/latest",
        "github": "https://github.com/mlflow/mlflow",
        "llms_txt": "https://mlflow.org/llms.txt",
        "llms_full_txt": None,
    },
    "transformers": {
        "description": "Pretrained model library and training utilities (Trainer)",
        "category": "core",
        "official_docs": "https://huggingface.co/docs/transformers",
        "github": "https://github.com/huggingface/transformers",
        "llms_txt": "https://huggingface.co/docs/transformers/llms.txt",
        "llms_full_txt": "https://huggingface.co/docs/transformers/llms-full.txt",
    },
    "datasets": {
        "description": "Loading, processing, and streaming of ML datasets",
        "category": "core",
        "official_docs": "https://huggingface.co/docs/datasets",
        "github": "https://github.com/huggingface/datasets",
        "llms_txt": "https://huggingface.co/docs/datasets/llms.txt",
        "llms_full_txt": "https://huggingface.co/docs/datasets/llms-full.txt",
    },
    "pytorch": {
        "description": "Core deep learning framework",
        "category": "core",
        "official_docs": "https://docs.pytorch.org/docs/stable",
        "github": "https://github.com/pytorch/pytorch",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "optuna": {
        "description": "Hyperparameter optimization framework (define-by-run search spaces, pruning)",
        "category": "hyperparameter_optimization",
        "official_docs": "https://optuna.readthedocs.io/en/stable",
        "github": "https://github.com/optuna/optuna",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "ax": {
        "description": "Adaptive experimentation platform for A/B tests and Bayesian optimization",
        "category": "hyperparameter_optimization",
        "official_docs": "https://ax.dev",
        "github": "https://github.com/facebook/Ax",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "botorch": {
        "description": "Bayesian optimization library built on PyTorch",
        "category": "hyperparameter_optimization",
        "official_docs": "https://botorch.org",
        "github": "https://github.com/meta-pytorch/botorch",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "tokenizers": {
        "description": "Fast tokenizers (BPE, WordPiece, Unigram) with training support",
        "category": "tokenization",
        "official_docs": "https://huggingface.co/docs/tokenizers/main/en/index",
        "github": "https://github.com/huggingface/tokenizers",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "sentencepiece": {
        "description": "Language-independent subword tokenizer (BPE, unigram)",
        "category": "tokenization",
        "official_docs": "https://github.com/google/sentencepiece",
        "github": "https://github.com/google/sentencepiece",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "tiktoken": {
        "description": "Fast BPE tokenizer for OpenAI models",
        "category": "tokenization",
        "official_docs": "https://github.com/openai/tiktoken",
        "github": "https://github.com/openai/tiktoken",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "torchao": {
        "description": "PyTorch-native quantization and sparsity (weight-only, QAT, float8)",
        "category": "optimization",
        "official_docs": "https://docs.pytorch.org/ao",
        "github": "https://github.com/pytorch/ao",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "llm-compressor": {
        "description": "Model compression (GPTQ, AWQ, SmoothQuant, sparsity) for vLLM deployment",
        "category": "optimization",
        "official_docs": "https://docs.vllm.ai/projects/llm-compressor/en/latest",
        "github": "https://github.com/vllm-project/llm-compressor",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "triton-lang": {
        "description": "Python DSL for writing custom GPU kernels",
        "category": "gpu_computing",
        "official_docs": "https://triton-lang.org",
        "github": "https://github.com/triton-lang/triton",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "cuda-toolkit": {
        "description": "NVIDIA CUDA Toolkit documentation (runtime, compiler, core libraries)",
        "category": "gpu_computing",
        "official_docs": "https://docs.nvidia.com/cuda",
        "github": None,
        "llms_txt": "https://docs.nvidia.com/cuda/llms.txt",
        "llms_full_txt": None,
    },
    "nccl": {
        "description": "NVIDIA multi-GPU/multi-node collective communication library",
        "category": "gpu_computing",
        "official_docs": "https://docs.nvidia.com/deeplearning/nccl/user-guide/docs",
        "github": "https://github.com/NVIDIA/nccl",
        "llms_txt": "https://docs.nvidia.com/llms.txt",
        "llms_full_txt": None,
    },
    "cutlass": {
        "description": "CUDA templates for high-performance GEMM kernels",
        "category": "gpu_computing",
        "official_docs": "https://docs.nvidia.com/cutlass",
        "github": "https://github.com/NVIDIA/cutlass",
        "llms_txt": "https://docs.nvidia.com/llms.txt",
        "llms_full_txt": None,
    },
    "transformer-engine": {
        "description": "FP8 training acceleration for transformers on NVIDIA GPUs",
        "category": "gpu_computing",
        "official_docs": "https://docs.nvidia.com/deeplearning/transformer-engine",
        "github": "https://github.com/NVIDIA/TransformerEngine",
        "llms_txt": "https://docs.nvidia.com/llms.txt",
        "llms_full_txt": None,
    },
    "rapids": {
        "description": "GPU dataframes and classical ML (cuDF, cuML)",
        "category": "gpu_computing",
        "official_docs": "https://docs.rapids.ai",
        "github": "https://github.com/rapidsai/cudf",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "nemo": {
        "description": "NVIDIA framework for large-scale LLM and multimodal training",
        "category": "distributed_training",
        "official_docs": "https://docs.nvidia.com/nemo-framework/user-guide/latest",
        "github": "https://github.com/NVIDIA-NeMo",
        "llms_txt": "https://docs.nvidia.com/nemo-framework/llms.txt",
        "llms_full_txt": None,
    },
    "triton-inference-server": {
        "description": "NVIDIA production inference server (multi-framework, ensembles)",
        "category": "inference_serving",
        "official_docs": "https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs",
        "github": "https://github.com/triton-inference-server/server",
        "llms_txt": "https://docs.nvidia.com/llms.txt",
        "llms_full_txt": None,
    },
    "dspy": {
        "description": "Programming framework for LLM pipelines with automatic prompt optimization",
        "category": "structured_output",
        "official_docs": "https://dspy.ai",
        "github": "https://github.com/stanfordnlp/dspy",
        "llms_txt": "https://dspy.ai/llms.txt",
        "llms_full_txt": None,
    },
    "outlines": {
        "description": "Constrained generation for structured LLM output (JSON, regex, grammars)",
        "category": "structured_output",
        "official_docs": "https://dottxt-ai.github.io/outlines",
        "github": "https://github.com/dottxt-ai/outlines",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "instructor": {
        "description": "Structured LLM outputs validated with Pydantic",
        "category": "structured_output",
        "official_docs": "https://python.useinstructor.com",
        "github": "https://github.com/567-labs/instructor",
        "llms_txt": "https://python.useinstructor.com/llms.txt",
        "llms_full_txt": None,
    },
    "faiss": {
        "description": "Efficient similarity search and clustering of dense vectors",
        "category": "rag_retrieval",
        "official_docs": "https://faiss.ai",
        "github": "https://github.com/facebookresearch/faiss",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "sentence-transformers": {
        "description": "Sentence and text embeddings, rerankers",
        "category": "rag_retrieval",
        "official_docs": "https://www.sbert.net",
        "github": "https://github.com/huggingface/sentence-transformers",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "chromadb": {
        "description": "Open-source embedding database for RAG",
        "category": "rag_retrieval",
        "official_docs": "https://docs.trychroma.com",
        "github": "https://github.com/chroma-core/chroma",
        "llms_txt": "https://docs.trychroma.com/llms.txt",
        "llms_full_txt": "https://docs.trychroma.com/llms-full.txt",
    },
    "qdrant": {
        "description": "Vector database with filtering and hybrid search",
        "category": "rag_retrieval",
        "official_docs": "https://qdrant.tech/documentation",
        "github": "https://github.com/qdrant/qdrant",
        "llms_txt": "https://qdrant.tech/llms.txt",
        "llms_full_txt": "https://qdrant.tech/llms-full.txt",
    },
    "langchain": {
        "description": "LLM application framework (chains, agents, integrations)",
        "category": "llm_orchestration",
        "official_docs": "https://docs.langchain.com",
        "github": "https://github.com/langchain-ai/langchain",
        "llms_txt": "https://docs.langchain.com/llms.txt",
        "llms_full_txt": "https://docs.langchain.com/llms-full.txt",
    },
    "langgraph": {
        "description": "Stateful multi-actor LLM agent graphs",
        "category": "llm_orchestration",
        "official_docs": "https://langchain-ai.github.io/langgraph",
        "github": "https://github.com/langchain-ai/langgraph",
        "llms_txt": "https://langchain-ai.github.io/langgraph/llms.txt",
        "llms_full_txt": None,
    },
    "litellm": {
        "description": "Unified API for 100+ LLM providers",
        "category": "llm_orchestration",
        "official_docs": "https://docs.litellm.ai",
        "github": "https://github.com/BerriAI/litellm",
        "llms_txt": "https://docs.litellm.ai/llms.txt",
        "llms_full_txt": "https://docs.litellm.ai/llms-full.txt",
    },
    "transformerlens": {
        "description": "Mechanistic interpretability of GPT-style models (activation caching and patching)",
        "category": "interpretability",
        "official_docs": "https://transformerlensorg.github.io/TransformerLens",
        "github": "https://github.com/TransformerLensOrg/TransformerLens",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "saelens": {
        "description": "Training and analyzing sparse autoencoders for interpretability",
        "category": "interpretability",
        "official_docs": "https://decoderesearch.github.io/SAELens",
        "github": "https://github.com/decoderesearch/SAELens",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "nnsight": {
        "description": "Intervening on internals of arbitrary PyTorch models (including remote)",
        "category": "interpretability",
        "official_docs": "https://nnsight.net",
        "github": "https://github.com/ndif-team/nnsight",
        "llms_txt": "https://nnsight.net/llms.txt",
        "llms_full_txt": None,
    },
    "pyvene": {
        "description": "Intervention-based interpretability experiments",
        "category": "interpretability",
        "official_docs": "https://github.com/stanfordnlp/pyvene",
        "github": "https://github.com/stanfordnlp/pyvene",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "captum": {
        "description": "Model attribution and interpretability for PyTorch",
        "category": "interpretability",
        "official_docs": "https://captum.ai",
        "github": "https://github.com/meta-pytorch/captum",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "lighteval": {
        "description": "Hugging Face LLM evaluation toolkit (multi-backend)",
        "category": "evaluation",
        "official_docs": "https://huggingface.co/docs/lighteval",
        "github": "https://github.com/huggingface/lighteval",
        "llms_txt": "https://huggingface.co/docs/lighteval/llms.txt",
        "llms_full_txt": "https://huggingface.co/docs/lighteval/llms-full.txt",
    },
    "inspect-ai": {
        "description": "UK AISI framework for LLM safety and capability evaluations",
        "category": "evaluation",
        "official_docs": "https://inspect.aisi.org.uk",
        "github": "https://github.com/UKGovernmentBEIS/inspect_ai",
        "llms_txt": "https://inspect.aisi.org.uk/llms.txt",
        "llms_full_txt": "https://inspect.aisi.org.uk/llms-full.txt",
    },
    "bigcode-evaluation-harness": {
        "description": "Code generation benchmark harness (HumanEval, MBPP, MultiPL-E)",
        "category": "evaluation",
        "official_docs": "https://github.com/bigcode-project/bigcode-evaluation-harness",
        "github": "https://github.com/bigcode-project/bigcode-evaluation-harness",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "gymnasium": {
        "description": "Standard API and environments for reinforcement learning",
        "category": "reinforcement_learning",
        "official_docs": "https://gymnasium.farama.org",
        "github": "https://github.com/Farama-Foundation/Gymnasium",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "pettingzoo": {
        "description": "Multi-agent reinforcement learning environments API",
        "category": "reinforcement_learning",
        "official_docs": "https://pettingzoo.farama.org",
        "github": "https://github.com/Farama-Foundation/PettingZoo",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "stable-baselines3": {
        "description": "Reliable PyTorch implementations of standard RL algorithms",
        "category": "reinforcement_learning",
        "official_docs": "https://stable-baselines3.readthedocs.io/en/master",
        "github": "https://github.com/DLR-RM/stable-baselines3",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "cleanrl": {
        "description": "Single-file, research-friendly RL algorithm implementations",
        "category": "reinforcement_learning",
        "official_docs": "https://docs.cleanrl.dev",
        "github": "https://github.com/vwxyzjn/cleanrl",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "torchrl": {
        "description": "PyTorch-native RL library (TensorDict-based)",
        "category": "reinforcement_learning",
        "official_docs": "https://docs.pytorch.org/rl",
        "github": "https://github.com/pytorch/rl",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "mujoco": {
        "description": "Physics engine for robotics and biomechanics simulation",
        "category": "simulation",
        "official_docs": "https://mujoco.readthedocs.io/en/stable",
        "github": "https://github.com/google-deepmind/mujoco",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "isaac-lab": {
        "description": "GPU-parallel robot learning framework on Isaac Sim",
        "category": "simulation",
        "official_docs": "https://isaac-sim.github.io/IsaacLab",
        "github": "https://github.com/isaac-sim/IsaacLab",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "pybullet": {
        "description": "Python physics simulation for robotics and RL",
        "category": "simulation",
        "official_docs": "https://pybullet.org",
        "github": "https://github.com/bulletphysics/bullet3",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "brax": {
        "description": "Differentiable JAX-based physics engine for RL at scale",
        "category": "simulation",
        "official_docs": "https://github.com/google/brax",
        "github": "https://github.com/google/brax",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "dm-control": {
        "description": "DeepMind control suite and MuJoCo-based RL environments",
        "category": "simulation",
        "official_docs": "https://github.com/google-deepmind/dm_control",
        "github": "https://github.com/google-deepmind/dm_control",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "maniskill": {
        "description": "GPU-parallelized robot manipulation benchmark and simulator",
        "category": "simulation",
        "official_docs": "https://maniskill.readthedocs.io/en/latest",
        "github": "https://github.com/mani-skill/ManiSkill",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "habitat-lab": {
        "description": "Embodied AI simulation platform (navigation, rearrangement)",
        "category": "simulation",
        "official_docs": "https://aihabitat.org",
        "github": "https://github.com/facebookresearch/habitat-lab",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "timm": {
        "description": "PyTorch image models (backbones, augmentations, training recipes)",
        "category": "vision",
        "official_docs": "https://huggingface.co/docs/timm",
        "github": "https://github.com/huggingface/pytorch-image-models",
        "llms_txt": "https://huggingface.co/docs/timm/llms.txt",
        "llms_full_txt": "https://huggingface.co/docs/timm/llms-full.txt",
    },
    "torchvision": {
        "description": "Vision datasets, transforms, and pretrained models for PyTorch",
        "category": "vision",
        "official_docs": "https://docs.pytorch.org/vision/stable",
        "github": "https://github.com/pytorch/vision",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "diffusers": {
        "description": "Diffusion model pipelines, schedulers, and training",
        "category": "vision",
        "official_docs": "https://huggingface.co/docs/diffusers",
        "github": "https://github.com/huggingface/diffusers",
        "llms_txt": "https://huggingface.co/docs/diffusers/llms.txt",
        "llms_full_txt": "https://huggingface.co/docs/diffusers/llms-full.txt",
    },
    "open-clip": {
        "description": "Open-source CLIP training and pretrained checkpoints",
        "category": "vision",
        "official_docs": "https://github.com/mlfoundations/open_clip",
        "github": "https://github.com/mlfoundations/open_clip",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "ultralytics": {
        "description": "YOLO family detection and segmentation training/deployment",
        "category": "vision",
        "official_docs": "https://docs.ultralytics.com",
        "github": "https://github.com/ultralytics/ultralytics",
        "llms_txt": "https://docs.ultralytics.com/llms.txt",
        "llms_full_txt": None,
    },
    "sam2": {
        "description": "Promptable image and video segmentation (Segment Anything 2)",
        "category": "vision",
        "official_docs": "https://github.com/facebookresearch/sam2",
        "github": "https://github.com/facebookresearch/sam2",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "kornia": {
        "description": "Differentiable computer vision operators for PyTorch",
        "category": "vision",
        "official_docs": "https://kornia.readthedocs.io/en/latest",
        "github": "https://github.com/kornia/kornia",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "whisper": {
        "description": "Robust speech recognition model and inference code",
        "category": "audio",
        "official_docs": "https://github.com/openai/whisper",
        "github": "https://github.com/openai/whisper",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "faster-whisper": {
        "description": "CTranslate2-accelerated Whisper inference",
        "category": "audio",
        "official_docs": "https://github.com/SYSTRAN/faster-whisper",
        "github": "https://github.com/SYSTRAN/faster-whisper",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "torchaudio": {
        "description": "Audio I/O, transforms, and models for PyTorch",
        "category": "audio",
        "official_docs": "https://docs.pytorch.org/audio/stable",
        "github": "https://github.com/pytorch/audio",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "espnet": {
        "description": "End-to-end speech processing toolkit (ASR, TTS, translation)",
        "category": "audio",
        "official_docs": "https://espnet.github.io/espnet",
        "github": "https://github.com/espnet/espnet",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "speechbrain": {
        "description": "PyTorch conversational AI toolkit (ASR, speaker, enhancement)",
        "category": "audio",
        "official_docs": "https://speechbrain.readthedocs.io/en/latest",
        "github": "https://github.com/speechbrain/speechbrain",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "jax": {
        "description": "Composable transformations (grad, jit, vmap) with XLA",
        "category": "jax_ecosystem",
        "official_docs": "https://docs.jax.dev",
        "github": "https://github.com/jax-ml/jax",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "flax": {
        "description": "Neural network library for JAX (NNX/Linen)",
        "category": "jax_ecosystem",
        "official_docs": "https://flax.readthedocs.io/en/latest",
        "github": "https://github.com/google/flax",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "optax": {
        "description": "Gradient transformation and optimizer library for JAX",
        "category": "jax_ecosystem",
        "official_docs": "https://optax.readthedocs.io/en/latest",
        "github": "https://github.com/google-deepmind/optax",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "equinox": {
        "description": "PyTorch-like neural networks as JAX PyTrees",
        "category": "jax_ecosystem",
        "official_docs": "https://docs.kidger.site/equinox",
        "github": "https://github.com/patrick-kidger/equinox",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "litgpt": {
        "description": "Hackable implementations of 20+ LLM architectures",
        "category": "architecture_research",
        "official_docs": "https://github.com/Lightning-AI/litgpt",
        "github": "https://github.com/Lightning-AI/litgpt",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "torchtitan": {
        "description": "PyTorch-native pretraining at scale (4D parallelism reference)",
        "category": "architecture_research",
        "official_docs": "https://github.com/pytorch/torchtitan",
        "github": "https://github.com/pytorch/torchtitan",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "mamba": {
        "description": "Selective state space model architecture reference implementation",
        "category": "architecture_research",
        "official_docs": "https://github.com/state-spaces/mamba",
        "github": "https://github.com/state-spaces/mamba",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "datatrove": {
        "description": "Large-scale text data processing and deduplication pipelines",
        "category": "data_processing",
        "official_docs": "https://github.com/huggingface/datatrove",
        "github": "https://github.com/huggingface/datatrove",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "webdataset": {
        "description": "Streaming tar-based dataset format for large-scale training",
        "category": "data_processing",
        "official_docs": "https://github.com/webdataset/webdataset",
        "github": "https://github.com/webdataset/webdataset",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "polars": {
        "description": "Fast dataframe library (lazy, multi-threaded)",
        "category": "data_processing",
        "official_docs": "https://docs.pola.rs",
        "github": "https://github.com/pola-rs/polars",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "duckdb": {
        "description": "In-process analytical SQL database",
        "category": "data_processing",
        "official_docs": "https://duckdb.org/docs",
        "github": "https://github.com/duckdb/duckdb",
        "llms_txt": "https://duckdb.org/llms.txt",
        "llms_full_txt": None,
    },
    "nemo-curator": {
        "description": "GPU-accelerated data curation for LLM training",
        "category": "data_processing",
        "official_docs": "https://docs.nvidia.com/nemo/curator/latest",
        "github": "https://github.com/NVIDIA-NeMo/Curator",
        "llms_txt": "https://docs.nvidia.com/nemo/curator/latest/llms.txt",
        "llms_full_txt": "https://docs.nvidia.com/nemo/curator/latest/llms-full.txt",
    },
    "scikit-learn": {
        "description": "Classical ML algorithms, model selection, and metrics",
        "category": "classical_ml_statistics",
        "official_docs": "https://scikit-learn.org/stable",
        "github": "https://github.com/scikit-learn/scikit-learn",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "scipy": {
        "description": "Scientific computing (optimization, stats, signal processing)",
        "category": "classical_ml_statistics",
        "official_docs": "https://docs.scipy.org/doc/scipy",
        "github": "https://github.com/scipy/scipy",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "statsmodels": {
        "description": "Statistical models and hypothesis tests (regression, GLM, ANOVA)",
        "category": "classical_ml_statistics",
        "official_docs": "https://www.statsmodels.org/stable",
        "github": "https://github.com/statsmodels/statsmodels",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "pymc": {
        "description": "Bayesian modeling with MCMC and variational inference",
        "category": "classical_ml_statistics",
        "official_docs": "https://www.pymc.io",
        "github": "https://github.com/pymc-devs/pymc",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "numpyro": {
        "description": "JAX-backed probabilistic programming (NUTS at scale)",
        "category": "classical_ml_statistics",
        "official_docs": "https://num.pyro.ai",
        "github": "https://github.com/pyro-ppl/numpyro",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "cvxpy": {
        "description": "Modeling language for convex optimization",
        "category": "mathematical_optimization",
        "official_docs": "https://www.cvxpy.org",
        "github": "https://github.com/cvxpy/cvxpy",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "pyomo": {
        "description": "Algebraic modeling for LP/MIP/NLP with solver interfaces",
        "category": "mathematical_optimization",
        "official_docs": "https://pyomo.readthedocs.io/en/stable",
        "github": "https://github.com/Pyomo/pyomo",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "ortools": {
        "description": "Google's combinatorial optimization (CP-SAT, routing, LP)",
        "category": "mathematical_optimization",
        "official_docs": "https://developers.google.com/optimization",
        "github": "https://github.com/google/or-tools",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "dowhy": {
        "description": "Causal inference with explicit assumptions and refutation tests",
        "category": "causal_inference",
        "official_docs": "https://www.pywhy.org/dowhy",
        "github": "https://github.com/py-why/dowhy",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "econml": {
        "description": "Heterogeneous treatment effect estimation (DML, DR, meta-learners)",
        "category": "causal_inference",
        "official_docs": "https://econml.azurewebsites.net",
        "github": "https://github.com/py-why/EconML",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "causalml": {
        "description": "Uplift modeling and causal machine learning",
        "category": "causal_inference",
        "official_docs": "https://causalml.readthedocs.io/en/latest",
        "github": "https://github.com/uber/causalml",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "darts": {
        "description": "Unified forecasting library (classical to deep models)",
        "category": "time_series",
        "official_docs": "https://unit8co.github.io/darts",
        "github": "https://github.com/unit8co/darts",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "sktime": {
        "description": "scikit-learn-compatible time series learning framework",
        "category": "time_series",
        "official_docs": "https://www.sktime.net",
        "github": "https://github.com/sktime/sktime",
        "llms_txt": "https://www.sktime.net/llms.txt",
        "llms_full_txt": None,
    },
    "statsforecast": {
        "description": "Fast classical forecasting (ARIMA, ETS) at scale",
        "category": "time_series",
        "official_docs": "https://nixtlaverse.nixtla.io/statsforecast",
        "github": "https://github.com/Nixtla/statsforecast",
        "llms_txt": "https://nixtlaverse.nixtla.io/llms.txt",
        "llms_full_txt": "https://nixtlaverse.nixtla.io/llms-full.txt",
    },
    "neuralforecast": {
        "description": "Deep learning forecasting models (NBEATS, NHITS, TFT)",
        "category": "time_series",
        "official_docs": "https://nixtlaverse.nixtla.io/neuralforecast",
        "github": "https://github.com/Nixtla/neuralforecast",
        "llms_txt": "https://nixtlaverse.nixtla.io/llms.txt",
        "llms_full_txt": "https://nixtlaverse.nixtla.io/llms-full.txt",
    },
    "gluonts": {
        "description": "Probabilistic time series modeling",
        "category": "time_series",
        "official_docs": "https://ts.gluon.ai",
        "github": "https://github.com/awslabs/gluonts",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "torch-geometric": {
        "description": "Graph neural networks for PyTorch",
        "category": "graph_learning",
        "official_docs": "https://pytorch-geometric.readthedocs.io/en/latest",
        "github": "https://github.com/pyg-team/pytorch_geometric",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "monai": {
        "description": "Deep learning framework for medical imaging",
        "category": "scientific_ml",
        "official_docs": "https://monai.readthedocs.io/en/stable",
        "github": "https://github.com/Project-MONAI/MONAI",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "rdkit": {
        "description": "Cheminformatics toolkit (molecules, descriptors, reactions)",
        "category": "scientific_ml",
        "official_docs": "https://www.rdkit.org/docs",
        "github": "https://github.com/rdkit/rdkit",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "deepchem": {
        "description": "ML for drug discovery, chemistry, and materials",
        "category": "scientific_ml",
        "official_docs": "https://deepchem.readthedocs.io/en/latest",
        "github": "https://github.com/deepchem/deepchem",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "physicsnemo": {
        "description": "Physics-ML framework (neural operators, PINNs)",
        "category": "scientific_ml",
        "official_docs": "https://docs.nvidia.com/physicsnemo",
        "github": "https://github.com/NVIDIA/physicsnemo",
        "llms_txt": "https://docs.nvidia.com/llms.txt",
        "llms_full_txt": None,
    },
    "esm": {
        "description": "Protein language models (ESM3, ESM C)",
        "category": "scientific_ml",
        "official_docs": "https://github.com/evolutionaryscale/esm",
        "github": "https://github.com/Biohub/esm",
        "llms_txt": None,
        "llms_full_txt": None,
    },
    "nemo-guardrails": {
        "description": "Programmable guardrails for LLM applications",
        "category": "safety",
        "official_docs": "https://docs.nvidia.com/nemo/guardrails",
        "github": "https://github.com/NVIDIA-NeMo/Guardrails",
        "llms_txt": "https://docs.nvidia.com/nemo/guardrails/llms.txt",
        "llms_full_txt": "https://docs.nvidia.com/nemo/guardrails/llms-full.txt",
    },
}
