# Curated model registry — audio / speech. Part of the shared
# domain>category taxonomy across resources/{libraries,models,datasets}.
# HuggingFace URLs and arXiv citations are verified on entry; use
# search_huggingface_hub for un-curated needs.
SPEECH_MODELS: dict = {
    "whisper-large-v3": {
        "description": "",
        "model_parameters": "1.5B",
        "model_architecture": "Speech model for automatic speech recognition.",
        "domain": "audio",
        "category": "speech",
        "task_type": "automatic-speech-recognition",
        "huggingface_url": "https://huggingface.co/openai/whisper-large-v3",
        "dependent_packages": ["transformers", "torch"],
        "code": """from transformers import pipeline
pipe = pipeline("automatic-speech-recognition", model="openai/whisper-large-v3")""",
        "citation": """@misc{radford2022,
  title = {Robust Speech Recognition via Large-Scale Weak Supervision},
  author = {Alec Radford and Jong Wook Kim and Tao Xu and Greg Brockman and Christine McLeavey and Ilya Sutskever},
  year = {2022},
  eprint = {2212.04356},
  archivePrefix = {arXiv},
  url = {https://arxiv.org/abs/2212.04356}
}""",
        "training_data_sources": "",
    },
    "wav2vec2-base-960h": {
        "description": "",
        "model_parameters": "94M",
        "model_architecture": "Speech model for automatic speech recognition.",
        "domain": "audio",
        "category": "speech",
        "task_type": "automatic-speech-recognition",
        "huggingface_url": "https://huggingface.co/facebook/wav2vec2-base-960h",
        "dependent_packages": ["transformers", "torch"],
        "code": """from transformers import pipeline
pipe = pipeline("automatic-speech-recognition", model="facebook/wav2vec2-base-960h")""",
        "citation": """@misc{baevski2020,
  title = {wav2vec 2.0: A Framework for Self-Supervised Learning of Speech Representations},
  author = {Alexei Baevski and Henry Zhou and Abdelrahman Mohamed and Michael Auli},
  year = {2020},
  eprint = {2006.11477},
  archivePrefix = {arXiv},
  url = {https://arxiv.org/abs/2006.11477}
}""",
        "training_data_sources": "",
    },
    "hubert-base-ls960": {
        "description": "",
        "model_parameters": "Unknown",
        "model_architecture": "Speech model for automatic speech recognition.",
        "domain": "audio",
        "category": "speech",
        "task_type": "automatic-speech-recognition",
        "huggingface_url": "https://huggingface.co/facebook/hubert-base-ls960",
        "dependent_packages": ["transformers", "torch"],
        "code": """from transformers import pipeline
pipe = pipeline("automatic-speech-recognition", model="facebook/hubert-base-ls960")""",
        "citation": """@misc{hsu2021,
  title = {HuBERT: Self-Supervised Speech Representation Learning by Masked Prediction of Hidden Units},
  author = {Wei-Ning Hsu and Benjamin Bolte and Yao-Hung Hubert Tsai and Kushal Lakhotia and Ruslan Salakhutdinov and Abdelrahman Mohamed},
  year = {2021},
  eprint = {2106.07447},
  archivePrefix = {arXiv},
  url = {https://arxiv.org/abs/2106.07447}
}""",
        "training_data_sources": "",
    },
    "whisper-small": {
        "description": "",
        "model_parameters": "242M",
        "model_architecture": "Speech/audio model.",
        "domain": "audio",
        "category": "speech",
        "task_type": "automatic-speech-recognition",
        "huggingface_url": "https://huggingface.co/openai/whisper-small",
        "dependent_packages": ["transformers", "torch"],
        "code": """from transformers import pipeline
pipe = pipeline("automatic-speech-recognition", model="openai/whisper-small")""",
        "citation": """@misc{radford2022,
  title = {Robust Speech Recognition via Large-Scale Weak Supervision},
  author = {Alec Radford and Jong Wook Kim and Tao Xu and Greg Brockman and Christine McLeavey and Ilya Sutskever},
  year = {2022},
  eprint = {2212.04356},
  archivePrefix = {arXiv},
  url = {https://arxiv.org/abs/2212.04356}
}""",
        "training_data_sources": "",
    },
    "mms-1b-all": {
        "description": "",
        "model_parameters": "965M",
        "model_architecture": "Speech/audio model.",
        "domain": "audio",
        "category": "speech",
        "task_type": "automatic-speech-recognition",
        "huggingface_url": "https://huggingface.co/facebook/mms-1b-all",
        "dependent_packages": ["transformers", "torch"],
        "code": """from transformers import pipeline
pipe = pipeline("automatic-speech-recognition", model="facebook/mms-1b-all")""",
        "citation": """@misc{pratap2023,
  title = {Scaling Speech Technology to 1,000+ Languages},
  author = {Vineel Pratap and Andros Tjandra and Bowen Shi and Paden Tomasello and Arun Babu and Sayani Kundu and Ali Elkahky and Zhaoheng Ni and Apoorv Vyas and Maryam Fazel-Zarandi and Alexei Baevski and Yossi Adi and Xiaohui Zhang and Wei-Ning Hsu and Alexis Conneau and Michael Auli},
  year = {2023},
  eprint = {2305.13516},
  archivePrefix = {arXiv},
  url = {https://arxiv.org/abs/2305.13516}
}""",
        "training_data_sources": "",
    },
    "speecht5-tts": {
        "description": "",
        "model_parameters": "Unknown",
        "model_architecture": "Speech/audio model.",
        "domain": "audio",
        "category": "speech",
        "task_type": "text-to-speech",
        "huggingface_url": "https://huggingface.co/microsoft/speecht5_tts",
        "dependent_packages": ["transformers", "torch"],
        "code": """from transformers import pipeline
pipe = pipeline("text-to-speech", model="microsoft/speecht5_tts")""",
        "citation": """@misc{ao2021,
  title = {SpeechT5: Unified-Modal Encoder-Decoder Pre-Training for Spoken Language Processing},
  author = {Junyi Ao and Rui Wang and Long Zhou and Chengyi Wang and Shuo Ren and Yu Wu and Shujie Liu and Tom Ko and Qing Li and Yu Zhang and Zhihua Wei and Yao Qian and Jinyu Li and Furu Wei},
  year = {2021},
  eprint = {2110.07205},
  archivePrefix = {arXiv},
  url = {https://arxiv.org/abs/2110.07205}
}""",
        "training_data_sources": "",
    },
    "musicgen-small": {
        "description": "",
        "model_parameters": "591M",
        "model_architecture": "Speech/audio model.",
        "domain": "audio",
        "category": "speech",
        "task_type": "text-to-audio",
        "huggingface_url": "https://huggingface.co/facebook/musicgen-small",
        "dependent_packages": ["transformers", "torch"],
        "code": """from transformers import pipeline
pipe = pipeline("text-to-audio", model="facebook/musicgen-small")""",
        "citation": """@misc{copet2023,
  title = {Simple and Controllable Music Generation},
  author = {Jade Copet and Felix Kreuk and Itai Gat and Tal Remez and David Kant and Gabriel Synnaeve and Yossi Adi and Alexandre Défossez},
  year = {2023},
  eprint = {2306.05284},
  archivePrefix = {arXiv},
  url = {https://arxiv.org/abs/2306.05284}
}""",
        "training_data_sources": "",
    },
}
