"""The record's literature as BibTeX, and the keys \\cite uses."""

from __future__ import annotations

import bibtexparser
from bibtexparser.bibdatabase import BibDatabase

from airas.core.types.research_record import LiteratureSource
from airas.usecases.writers.generate_bibfile_subgraph.nodes.generate_bibfile import (
    _disambiguation_suffix,
    _generate_citation_key,
)


def unique_bibkey(
    title: str, authors: list[str], year: int | None, taken: set[str]
) -> str:
    base = _generate_citation_key(title, authors, year)
    key, occurrence = base, 0
    while key in taken:
        occurrence += 1
        key = f"{base}{_disambiguation_suffix(occurrence)}"
    return key


def render_references_bib(literature: list[LiteratureSource]) -> str:
    """One entry per source under its bibkey; regenerated by the gate."""
    db = BibDatabase()
    for source in literature:
        entry = {
            "ID": source.bibkey,
            "ENTRYTYPE": "article" if source.kind == "paper" else "misc",
            "title": source.title,
        }
        if source.authors:
            entry["author"] = " and ".join(source.authors)
        if source.year:
            entry["year"] = str(source.year)
        if source.venue:
            entry["journal"] = source.venue
        if source.doi:
            entry["doi"] = source.doi
        if source.url:
            entry["url"] = source.url
        if source.commit:
            entry["note"] = f"commit {source.commit}"
        db.entries.append(entry)
    return bibtexparser.dumps(db).strip() + "\n"
