name: Deploy Docs to GitHub Pages

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'docs/**'
      - '.github/workflows/upload_github_pages.yml'

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install
        working-directory: docs

      - name: Build Docusaurus site
        run: yarn build
        working-directory: docs

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn deploy
        working-directory: docs
